[profile.default]
solc-version = "0.8.19"
gas_reports = ["SuperRouter", "SuperDestination", "MultiTxProcessor"]
libraries = []
optimizer = true
optimizer_runs = 200
remappings = [
  '@openzeppelin-contracts=lib/openzeppelin-contracts/contracts',
  '@openzeppelin-contracts-upgradeable=lib/openzeppelin-contracts-upgradeable/contracts',
  '@pigeon=lib/pigeon/src/',
  '@ds-test=lib/ds-test/src/',
  '@std=lib/forge-std/src/',
  '@solmate=lib/solmate/src/',
  '@erc1155s=lib/erc1155s/src/'
]
test = 'src/test'
verbosity = 0
ffi = true
libs = ["lib"]
