[profile.default]
solc-version = "0.8.19"
gas_reports = ["SuperRouter", "SuperDestination", "MultiTxProcessor"]
libraries = []
optimizer = true
optimizer_runs = 200
test = 'src/test'
verbosity = 0
ffi = true
libs = ["lib"]
